#!/usr/bin/env python3
"""
Touri Backend — Self-Testing Diagnostic & Auto-Repair Pipeline.

Run:  cd backend && python3 check_backend.py

Verifies every core subsystem needed for the defense demo and auto-repairs
fixable issues (missing .env, stale model names, ChromaDB connectivity).
"""

from __future__ import annotations

import os
import sys
import time
from pathlib import Path

# ── Resolve paths relative to this script ────────────────────────────────────
BACKEND_DIR = Path(__file__).resolve().parent
ENV_FILE = BACKEND_DIR / ".env"
DATA_DIR = BACKEND_DIR / "data"
EGYPT_CSV_DIR = DATA_DIR / "egypt_csv"
CHROMA_DIR = DATA_DIR / "chroma_db"

# SECURITY: API keys are NEVER hardcoded here. They must be present in .env.
TARGET_API_KEY: str = ""  # Populated from .env only — see step1_env_validation()
TARGET_MODEL = "mistral-large-latest"
CHROMA_COLLECTION = "egypt_travel_knowledge"

MANDATORY_CSV_FILES = [
    "egypt_hotels_completed.csv",          # hotels
    "FINAL _Atrreaction dataset.csv",       # attractions
    "Egypt_Restaurants.csv",                # restaurants
    "events.csv",                           # events
    "flights_data_egypt_with_realistic_prices.csv",  # flights
    "Egypt_Transportation_Realistic_Expanded.csv",   # transportation
    "medical_tourism_prices_egp_converted.xlsx",     # medical
]

passed = 0
failed = 0
repaired = 0


def ok(msg: str) -> None:
    global passed
    passed += 1
    print(f"  ✅ {msg}")


def fail(msg: str) -> None:
    global failed
    failed += 1
    print(f"  ❌ {msg}")


def repair(msg: str) -> None:
    global repaired
    repaired += 1
    print(f"  🔧 {msg}")


def warn(msg: str) -> None:
    print(f"  ⚠️  {msg}")


def header(title: str) -> None:
    print(f"\n{'─' * 60}")
    print(f"  {title}")
    print(f"{'─' * 60}")


# ═══════════════════════════════════════════════════════════════════════════════
#  STEP 1: Environment File Validation
# ═══════════════════════════════════════════════════════════════════════════════
def step1_env_validation() -> dict[str, str]:
    header("STEP 1: Environment File Validation (.env)")

    env_vars: dict[str, str] = {}

    # Check .env existence
    if not ENV_FILE.exists():
        fail(f".env file NOT FOUND at {ENV_FILE}")
        repair("Auto-generating .env with required credentials...")
        _generate_env()
        if ENV_FILE.exists():
            ok(".env auto-generated successfully")
        else:
            fail("Failed to auto-generate .env")
            return env_vars
    else:
        ok(f".env file exists at {ENV_FILE}")

    # Parse .env
    with open(ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                env_vars[key.strip()] = value.strip()

    # Check MISTRAL_API_KEY — never inject or overwrite; must be set manually
    mistral_key = env_vars.get("MISTRAL_API_KEY", "")
    if not mistral_key:
        fail("MISTRAL_API_KEY is EMPTY or MISSING in .env")
        warn("  → Set it manually: echo 'MISTRAL_API_KEY=your_key' >> .env")
    else:
        ok(f"MISTRAL_API_KEY is set: {mistral_key[:8]}...{mistral_key[-4:]}")

    # Check model names — only auto-fix if unset (never overwrite user config)
    pro_model = env_vars.get("MISTRAL_PRO_MODEL", "")
    fast_model = env_vars.get("MISTRAL_FAST_MODEL", "")
    if pro_model == TARGET_MODEL:
        ok(f"MISTRAL_PRO_MODEL = {TARGET_MODEL}")
    elif not pro_model:
        repair(f"MISTRAL_PRO_MODEL not set → defaulting to {TARGET_MODEL}")
        _inject_env_var("MISTRAL_PRO_MODEL", TARGET_MODEL)
    else:
        warn(f"MISTRAL_PRO_MODEL = '{pro_model}' (expected '{TARGET_MODEL}')")

    if fast_model == "mistral-small-latest":
        ok("MISTRAL_FAST_MODEL = mistral-small-latest")
    elif not fast_model:
        repair("MISTRAL_FAST_MODEL not set → defaulting to mistral-small-latest")
        _inject_env_var("MISTRAL_FAST_MODEL", "mistral-small-latest")
    else:
        warn(f"MISTRAL_FAST_MODEL = '{fast_model}' (expected 'mistral-small-latest')")

    # Check Firebase credentials path
    fb_path = env_vars.get("FIREBASE_CREDENTIALS_PATH", "")
    if fb_path:
        abs_fb = Path(fb_path)
        if not abs_fb.is_absolute():
            abs_fb = (BACKEND_DIR / fb_path).resolve()
        if abs_fb.exists():
            ok(f"FIREBASE_CREDENTIALS_PATH exists: {fb_path}")
        else:
            warn(f"FIREBASE_CREDENTIALS_PATH points to missing file: {abs_fb}")
    else:
        warn("FIREBASE_CREDENTIALS_PATH is not set (Firestore will be unavailable)")

    return env_vars


def _generate_env() -> None:
    content = """\
# ── Auto-generated by check_backend.py ────────────────────────────────────────
# IMPORTANT: Fill in your credentials before running the backend.

# Google Gemini (primary LLM engine) — SET THIS MANUALLY
GEMINI_API_KEY=
GEMINI_PRO_MODEL=gemma-4-26b-a4b-it
GEMINI_FAST_MODEL=gemma-4-26b-a4b-it

# Session security — generate with: python3 -c "import secrets; print(secrets.token_urlsafe(64))"
SESSION_JWT_SECRET=

# External services
TAVILY_API_KEY=
OPENWEATHER_API_KEY=
FIREBASE_CREDENTIALS_PATH=secrets/firebase-service-account.json

# HTTP server
HOST=0.0.0.0
PORT=8000
# SECURITY: Set to your actual frontend origins in production. Never use * in production.
CORS_ORIGINS=http://localhost:8081,http://localhost:19006

# Environment: 'development' or 'production'
TOURI_ENV=development

# RAG / Chroma
EMBEDDING_BACKEND=sentence_transformers
"""
    ENV_FILE.write_text(content)


def _inject_env_var(key: str, value: str) -> None:
    if not ENV_FILE.exists():
        ENV_FILE.write_text(f"{key}={value}\n")
        return
    lines = ENV_FILE.read_text().splitlines()
    found = False
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith(f"{key}=") or stripped.startswith(f"{key} ="):
            lines[i] = f"{key}={value}"
            found = True
            break
    if not found:
        lines.append(f"{key}={value}")
    ENV_FILE.write_text("\n".join(lines) + "\n")


# ═══════════════════════════════════════════════════════════════════════════════
#  STEP 2: Mistral AI SDK Test Connection
# ═══════════════════════════════════════════════════════════════════════════════
def step2_mistral_connection(env_vars: dict[str, str]) -> None:
    header("STEP 2: Mistral AI SDK Test Connection")

    api_key = env_vars.get("MISTRAL_API_KEY", "")
    if not api_key:
        fail("MISTRAL_API_KEY is not set — skipping API connection test")
        return

    try:
        from mistralai.client import Mistral
        ok("mistralai SDK imported successfully")
    except ImportError:
        fail("mistralai is NOT installed")
        print("       Run: pip install mistralai")
        return

    try:
        client = Mistral(api_key=api_key)
        ok(f"Mistral client configured with API key: {api_key[:12]}...{api_key[-4:]}")
    except Exception as exc:
        fail(f"Mistral client configuration failed: {exc}")
        return

    # Lightweight model probe
    print(f"  🔄 Testing model '{TARGET_MODEL}' with a lightweight probe...")
    try:
        t0 = time.time()
        response = client.chat.complete(
            model=TARGET_MODEL,
            messages=[{"role": "user", "content": "Reply with only: OK"}],
            max_tokens=10,
        )
        elapsed = time.time() - t0
        text = (response.choices[0].message.content or "").strip()
        if text:
            ok(f"Model responded in {elapsed:.2f}s: \"{text[:50]}\"")
        else:
            warn(f"Model returned empty response in {elapsed:.2f}s (may be rate-limited)")
    except Exception as exc:
        exc_str = str(exc)
        if "429" in exc_str or "quota" in exc_str.lower() or "rate" in exc_str.lower():
            warn(f"Rate-limited (429) — API key is valid but quota exhausted: {exc_str[:80]}")
        elif "404" in exc_str or "not found" in exc_str.lower():
            fail(f"Model '{TARGET_MODEL}' not found on this API key. Error: {exc_str[:100]}")
        elif "403" in exc_str or "permission" in exc_str.lower():
            fail(f"API key lacks permission for '{TARGET_MODEL}': {exc_str[:100]}")
        else:
            fail(f"Mistral probe call failed: {exc_str[:120]}")


# ═══════════════════════════════════════════════════════════════════════════════
#  STEP 3: CSV Data Files Check
# ═══════════════════════════════════════════════════════════════════════════════
def step3_csv_check() -> None:
    header("STEP 3: CSV / Data File Paths Check")

    if not EGYPT_CSV_DIR.exists():
        fail(f"Directory NOT FOUND: {EGYPT_CSV_DIR}")
        return
    ok(f"Directory exists: {EGYPT_CSV_DIR}")

    actual_files = set(os.listdir(EGYPT_CSV_DIR))
    print(f"  📂 Found {len(actual_files)} file(s) in egypt_csv/")

    for expected in MANDATORY_CSV_FILES:
        if expected in actual_files:
            fpath = EGYPT_CSV_DIR / expected
            size_kb = fpath.stat().st_size / 1024
            ok(f"  {expected} ({size_kb:.0f} KB)")
        else:
            fail(f"  MISSING: {expected}")

    # Also check the datasets mirror directory
    datasets_dir = DATA_DIR / "datasets"
    if datasets_dir.exists():
        ds_files = set(os.listdir(datasets_dir))
        egypt_ds = [f for f in ds_files if not (datasets_dir / f).is_dir()]
        ok(f"  datasets/ mirror found with {len(egypt_ds)} Egypt file(s)")
    else:
        warn("  datasets/ mirror directory not found (non-blocking)")


# ═══════════════════════════════════════════════════════════════════════════════
#  STEP 4: ChromaDB Connectivity Test
# ═══════════════════════════════════════════════════════════════════════════════
def step4_chromadb_test() -> None:
    header("STEP 4: ChromaDB Connectivity Test")

    if not CHROMA_DIR.exists():
        fail(f"ChromaDB persist directory NOT FOUND: {CHROMA_DIR}")
        return
    ok(f"ChromaDB persist directory exists: {CHROMA_DIR}")

    # Check for sqlite file
    sqlite_path = CHROMA_DIR / "chroma.sqlite3"
    if sqlite_path.exists():
        size_mb = sqlite_path.stat().st_size / (1024 * 1024)
        ok(f"chroma.sqlite3 found ({size_mb:.1f} MB)")
    else:
        warn("chroma.sqlite3 not found — collection may need ingestion")

    try:
        import chromadb
        ok(f"chromadb SDK imported (version: {chromadb.__version__})")
    except ImportError:
        fail("chromadb is NOT installed. Run: pip install chromadb")
        return

    try:
        client = chromadb.PersistentClient(path=str(CHROMA_DIR))
        ok("ChromaDB PersistentClient initialized")
    except Exception as exc:
        fail(f"ChromaDB client init failed: {exc}")
        return

    # List collections
    try:
        collections = client.list_collections()
        col_names = [c.name for c in collections]
        ok(f"Collections found: {col_names}")
    except Exception as exc:
        fail(f"Failed to list collections: {exc}")
        return

    # Check target collection
    if CHROMA_COLLECTION not in col_names:
        fail(f"Collection '{CHROMA_COLLECTION}' NOT FOUND in ChromaDB")
        print(f"       Available: {col_names}")
        return

    try:
        collection = client.get_collection(CHROMA_COLLECTION)
        count = collection.count()
        if count > 0:
            ok(f"Collection '{CHROMA_COLLECTION}' loaded — {count} documents")
        else:
            fail(f"Collection '{CHROMA_COLLECTION}' is EMPTY (0 documents)")
            print("       Run the data ingestion pipeline to populate it.")
    except Exception as exc:
        fail(f"Failed to load collection '{CHROMA_COLLECTION}': {exc}")
        return

    # Sample query test
    try:
        results = collection.query(
            query_texts=["best hotels in Cairo"],
            n_results=3,
        )
        n_hits = len(results.get("documents", [[]])[0])
        if n_hits > 0:
            ok(f"Sample query returned {n_hits} hit(s) — vector search operational")
            # Show a snippet of the first hit
            first = (results["documents"][0][0] or "")[:80]
            print(f"       Preview: \"{first}...\"")
        else:
            warn("Sample query returned 0 hits — embeddings may need regeneration")
    except Exception as exc:
        warn(f"Sample query failed (may need matching embedding function): {exc}")


# ═══════════════════════════════════════════════════════════════════════════════
#  STEP 5: Backend Module Import Smoke Test
# ═══════════════════════════════════════════════════════════════════════════════
def step5_import_test() -> None:
    header("STEP 5: Backend Module Import Smoke Test")

    # Add backend dir to path so imports work
    if str(BACKEND_DIR) not in sys.path:
        sys.path.insert(0, str(BACKEND_DIR))

    modules = [
        ("config",                "Settings & env loader"),
        ("agents.llm",            "LLM factory (Gemma-4-26B-A4B-IT)"),
        ("agents.state",          "AgentState TypedDict"),
        ("agents.router_agent",   "Router agent"),
        ("agents.travel_planner", "Travel Planner agent"),
        ("agents.budget_specialist", "Budget Specialist agent"),
        ("agents.local_concierge",   "Local Concierge agent"),
        ("agents.general_chat",   "General Chat agent"),
        ("agents.graph",          "LangGraph wiring"),
        ("rag.vector_store",      "ChromaDB vector store"),
        ("memory.user_persona",   "Firestore UserPersona"),
    ]

    for mod_name, label in modules:
        try:
            __import__(mod_name)
            ok(f"{mod_name} — {label}")
        except Exception as exc:
            exc_short = str(exc)[:80]
            fail(f"{mod_name} — {label}: {exc_short}")

    # Verify the active model constant
    try:
        from agents.llm import DEFAULT_MODEL, FAST_MODEL
        if DEFAULT_MODEL == TARGET_MODEL:
            ok(f"DEFAULT_MODEL = '{DEFAULT_MODEL}'")
        else:
            fail(f"DEFAULT_MODEL = '{DEFAULT_MODEL}' (expected '{TARGET_MODEL}')")
        expected_fast = "mistral-small-latest" if "mistral" in TARGET_MODEL else TARGET_MODEL
        if FAST_MODEL == expected_fast:
            ok(f"FAST_MODEL = '{FAST_MODEL}'")
        else:
            fail(f"FAST_MODEL = '{FAST_MODEL}' (expected '{expected_fast}')")
    except Exception as exc:
        fail(f"Could not verify model constants: {exc}")

    # Verify no convert_system_message_to_human in LLM
    try:
        import inspect
        from agents import llm as llm_mod
        source = inspect.getsource(llm_mod)
        if "convert_system_message_to_human" in source:
            fail("DEPRECATED: convert_system_message_to_human found in agents/llm.py")
        else:
            ok("No deprecated convert_system_message_to_human flag found")
    except Exception:
        warn("Could not inspect llm.py source")

    # Verify Tavily is not imported in budget_specialist
    try:
        import inspect
        from agents import budget_specialist as bs_mod
        source = inspect.getsource(bs_mod)
        # Check for active (non-commented) tavily import
        active_tavily = False
        for line in source.splitlines():
            stripped = line.strip()
            if "search_live_travel_data" in stripped and not stripped.startswith("#"):
                active_tavily = True
                break
        if active_tavily:
            fail("budget_specialist.py still has ACTIVE Tavily import")
        else:
            ok("budget_specialist.py — Tavily fully bypassed")
    except Exception:
        warn("Could not inspect budget_specialist.py source")


# ═══════════════════════════════════════════════════════════════════════════════
#  MAIN
# ═══════════════════════════════════════════════════════════════════════════════
def main() -> None:
    print("")
    print("=" * 60)
    print("  🧠 Touri Backend — Diagnostic & Auto-Repair Pipeline")
    print("=" * 60)
    print(f"  Working dir : {BACKEND_DIR}")
    print(f"  Python      : {sys.version.split()[0]}")
    print(f"  Target model: {TARGET_MODEL}")

    env_vars = step1_env_validation()
    step2_mistral_connection(env_vars)
    step3_csv_check()
    step4_chromadb_test()
    step5_import_test()

    # ── Summary ──────────────────────────────────────────────────────────────
    total = passed + failed
    print("")
    print("=" * 60)
    print(f"  📊 RESULTS: {passed}/{total} passed, {failed} failed, {repaired} auto-repaired")
    print("=" * 60)
    if failed == 0:
        print("  🎉 All checks passed — backend is READY for defense demo!")
    elif failed <= 2:
        print("  ⚠️  Minor issues detected — review warnings above.")
    else:
        print("  🚨 Critical issues found — fix before running the backend.")
    print("")

    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
