"""
UI_TRIGGER security validation layer.

SECURITY: UI_TRIGGER blocks are ONLY valid when generated server-side by
the LangGraph agents. User-supplied trigger blocks MUST be stripped.

This module provides:
- Strict Pydantic schema validation for trigger payloads
- Allowlist of valid trigger actions
- Payload sanitization
- Origin verification (only backend-generated triggers pass)
"""

from __future__ import annotations

import json
import logging
import re
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, ValidationError

logger = logging.getLogger("touri.ui_trigger")


# ── Valid trigger action allowlist ────────────────────────────────────────────
class TriggerAction(str, Enum):
    SHOW_ITINERARY = "show_itinerary"
    SHOW_BUDGET = "show_budget"
    SHOW_MAP = "show_map"
    SHOW_PLACES = "show_places"
    NAVIGATE = "navigate"
    CONFIRM_PLAN = "confirm_plan"
    UPDATE_TRIP = "update_trip"
    SHOW_SUGGESTIONS = "show_suggestions"


# ── Trigger payload schemas ───────────────────────────────────────────────────
class UITriggerPayload(BaseModel):
    """Validated UI trigger payload."""

    action: TriggerAction
    data: Optional[Dict[str, Any]] = Field(default=None)
    target: Optional[str] = Field(default=None, max_length=200)
    label: Optional[str] = Field(default=None, max_length=200)


class ValidatedTrigger(BaseModel):
    """A fully validated and safe UI trigger."""

    action: str
    data: Optional[Dict[str, Any]] = None
    target: Optional[str] = None
    label: Optional[str] = None
    _server_generated: bool = True


# ── Trigger parsing ──────────────────────────────────────────────────────────
_TRIGGER_BLOCK_RE = re.compile(
    r"---\s*UI_TRIGGER\s*---\s*\n(.*?)(?:\n---|\Z)",
    re.DOTALL | re.IGNORECASE,
)


def strip_user_triggers(text: str) -> str:
    """Remove any UI_TRIGGER blocks from user-supplied text. SECURITY."""
    return _TRIGGER_BLOCK_RE.sub("", text).strip()


def validate_trigger_block(raw_block: str) -> Optional[ValidatedTrigger]:
    """
    Parse and validate a UI_TRIGGER JSON block from agent output.

    Returns a ValidatedTrigger if valid, None if malformed/rejected.
    Only call this on text generated by the backend agents.
    """
    try:
        # Try to extract JSON from the block
        json_match = re.search(r"\{.*\}", raw_block, re.DOTALL)
        if not json_match:
            logger.warning("[ui_trigger] no JSON found in trigger block")
            return None

        payload_str = json_match.group(0)
        payload_dict = json.loads(payload_str)

        # Validate against schema
        validated = UITriggerPayload(**payload_dict)

        return ValidatedTrigger(
            action=validated.action.value,
            data=validated.data,
            target=validated.target,
            label=validated.label,
        )

    except (json.JSONDecodeError, ValidationError) as exc:
        logger.warning("[ui_trigger] invalid trigger payload: %s", exc)
        return None
    except Exception as exc:  # noqa: BLE001
        logger.error("[ui_trigger] unexpected validation error: %s", exc)
        return None


def extract_and_validate_triggers(response_text: str) -> tuple[str, List[ValidatedTrigger]]:
    """
    Extract, validate, and separate UI_TRIGGER blocks from agent response.

    Returns:
        (clean_text_without_triggers, list_of_validated_triggers)
    """
    triggers: List[ValidatedTrigger] = []

    matches = _TRIGGER_BLOCK_RE.finditer(response_text)
    for match in matches:
        raw_content = match.group(1)
        validated = validate_trigger_block(raw_content)
        if validated:
            triggers.append(validated)
        else:
            logger.warning("[ui_trigger] rejected malformed trigger in response")

    # Remove trigger blocks from visible text
    clean_text = _TRIGGER_BLOCK_RE.sub("", response_text).strip()

    return clean_text, triggers
